api/app/views/views.py
from flask import Flask, Blueprint, request, session, jsonify
from app.forms.signup.forms import SignupForm
from app.forms.login.forms import Login
from app.forms.update.forms import Update
from app.forms.delete.forms import Delete
from app.utils.execute_user_db import UserService
from app.utils.execute_crypt_db import PortfolioService
from app.utils.execute_api import API
import json

user_page = Blueprint("user_page", __name__,
                      template_folder="templates")



@user_page.route("/signup", methods=["POST"])
def signup():
    # duplicete check user_name and user_mail
    user_service = UserService()
    error = user_service.register(json.loads(request.data))
    if error:
        return jsonify(ok=True)
    # alredy exist same user name or email
    return ""


@user_page.route("/login", methods=["POST"])
def login():
    # check if user already created a account
    user_service = UserService()
    user = user_service.login(json.loads(request.data))

    if user:
        session['user_id'] = user.user_id
        session['login'] = True

        print(session)
        # return user data
        return jsonify(id=user.user_id, username=user.user_name, mail=user.user_mail, password=user.user_password)
    # doesn't match post data with user info in db
    return ""


@user_page.route("/edit/<id>", methods=["PATCH"])
def edit(id):

    if session.get("user_id") != int(id):
        return ""

    user_service = UserService()
    response = user_service.update(json.loads(request.data), id)
    if response:
        return request.data

    return ""


@user_page.route("/delete/<id>", methods=["DELETE"])
def delete(id):

    if session.get("user_id") != int(id):
        return ""

    user_service = UserService()
    error = user_service.delete(id)
    if error:
        session.pop("user_id", None)
        session.pop("login", None)
        return jsonify(ok=True)
    return ""


@user_page.route("/fetch", methods=["GET"])
def fetch():

    if not is_login():
        return ""

    user_service = UserService()
    user = user_service.get_user_info_by_user_id(session["user_id"])

    return jsonify(id=user.user_id, username=user.user_name, email=user.user_mail, password=user.user_password)


@user_page.route("/refetch", methods=["GET"])
def refetch():

    if not is_login():
        return ""

    user_service = UserService()
    user = user_service.get_user_info_by_user_id(session["user_id"])

    return jsonify(id=user.user_id, username=user.user_name, email=user.user_mail, password=user.user_password)


@user_page.route("/logout/<id>", methods=["POST"])
def logout(id):

    if session.get("user_id") != int(id):
        return ""

    session.pop("user_id")
    session["login"] = False

    return jsonify(ok=True)


@user_page.route("/forgot_password", methods=["POST"])
def forgot_password():

    if not is_login():

        return ""

    response = json.loads(request.data)
    user_service = UserService()

    user = user_service.get_user_info_by_email(response["email"])

    if not user:
        return ""

    user_service.send_reset_mail(user)

    return jsonify(ok=True)


@user_page.route("/is_valid_token/<token>", methods=["POST"])
def is_valid_token(token):
    user_service = UserService()

    user = user_service.reset_password_by_token(token)
    if user is None:
        return ""

    return jsonify(ok=True)


@user_page.route("/reset_password/<token>", methods=["POST"])
def reset_password(token):
    form_data = json.loads(request.data)
    user_service = UserService()

    user = user_service.reset_password_by_token(token)
    if user is None:
        return ""

    result = user_service.register_new_password(user, form_data)
    if result:
        return jsonify(ok=True)
    return ""


@user_page.route("/fetch_currency", methods=["GET"])
def fetch_currency():
    if not is_login():

        return ""

    portfolio_service = PortfolioService()
    data = portfolio_service.get_user_portfolio(session["user_id"])
    if data:
        api = API()
        "data[0]: currency name, data[1]: number of hold currency"
        result = api.call_api(data[0])
        currency_list, total_value = api.data_process(result, data[1])
        return jsonify(id=session["user_id"], currency_list=currency_list, total_value=total_value)

    return jsonify(id=session["user_id"], currency_list="", total_value=0)


@user_page.route("/register_currency/<id>", methods=["POST"])
def register_currency(id):

    if not is_login():

        return ""

    request_data = json.loads(request.data)

    portfolio_service = PortfolioService()
    error = portfolio_service.register(
        id, request_data["symbol"].upper(), request_data["num_hold"])
    if error:
        return jsonify(ok=True)

    return ""


@user_page.route("/edit_currency/<id>", methods=["PATCH"])
def edit_currency(id):

    if not is_login():

        return ""

    edit_data = json.loads(request.data)
    portfolio_service = PortfolioService()
    result = portfolio_service.update_currency_data(
        id, edit_data["symbol"].upper(), edit_data["num_hold"])
    if result:

        return jsonify(json.loads(request.data))

    return ""


@user_page.route("/delete_currency/<id>/<currency>", methods=["DELETE"])
def delete_currency(id, currency):

    if not is_login():

        return ""

    portfolio_service = PortfolioService()
    result = portfolio_service.delete_currency_data(id, currency.upper())
    if result:
        return jsonify(ok=True)

    return ""


# Check login status
def is_login():
    return session["login"]

api/app/templates/portfolio/delete_currency.html
{% extends "base.html" %} {% block content %} 

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  {% with messages = get_flashed_messages() %} {% if messages %}
                  <p>
                    {{ messages }}
                  </p>
                  {% endif %} {% endwith %}
                  <h1 class="h4 text-gray-900 mb-4">Delete Currency</h1>
                </div>
                <form action="" method="post" class="user">

                  <div class="form-group">
                    <p>currency name</p></br> <input type="text" name="coin_name" value="{{ currency_name }}"/>
                  </div>
                  <div class="form-group">
                  </div>
                  <input type="submit" value="Delete" class="btn btn-primary btn-user btn-block"/>
                  <hr />
                </form>
                <div class="text-center">
                  <a
                    class="small"
                    href="{{ url_for('user_page.user_portfolio') }}"
                  >
                    >Back to Portfolio</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

api/app/templates/portfolio/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width,
    initial-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>ES6</title>
  </head>
  <body>
    <h1>ES6 Refresher</h1>
    <script src="main.js"></script>
  </body>
</html>

api/app/templates/portfolio/register_currency.html
{% extends "base.html" %} {% block content %} 

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  {% with messages = get_flashed_messages() %} {% if messages %}
                  <p>
                    {{ messages }}
                  </p>
                  {% endif %} {% endwith %}
                  <h1 class="h4 text-gray-900 mb-4">Register New Cryptocurrency</h1>
                </div>
                <form action="" method="post" class="user">

                  <div class="form-group">
                    <p>currency name</p></br>
                    <input type="text" name="coin_name" />
                  </div>
                  <div class="form-group">                
                    <p>number of currency</p></br> 
                    <input type="number" step="0.0001" name="num_of_currency" value="0"/>
                  </div>
                  <div class="form-group">
                  </div>
                  <input type="submit" value="Register" class="btn btn-primary btn-user btn-block"/>
                  <hr />
                </form>
                <div class="text-center">
                  <a
                    class="small"
                    href="{{ url_for('user_page.user_portfolio') }}"
                  >
                    >Back to Portfolio</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

api/app/templates/portfolio/update_currency.html
{% extends "base.html" %} {% block content %} 

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  {% with messages = get_flashed_messages() %} {% if messages %}
                  <p>
                    {{ messages }}
                  </p>
                  {% endif %} {% endwith %}
                  <h1 class="h4 text-gray-900 mb-4">Update Currency</h1>
                </div>
                <form action="" method="post" class="user">

                  <div class="form-group">
                    <p>currency name</p></br>
                    <input type="text" name="coin_name" value="{{ currency_name }}"/>
                  </div>
                  <div class="form-group">
                    <p>number of currency</p></br> 
                    <input type="number" step="0.0001" name="num_of_currency" value="0"/>
                  </div>
                  <div class="form-group">
                  </div>
                  <input type="submit" value="update" class="btn btn-primary btn-user btn-block"/>
                  <hr />
                </form>
                <div class="text-center">
                  <a
                    class="small"
                    href="{{ url_for('user_page.user_portfolio') }}"
                  >
                    >Back to Portfolio</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

api/app/templates/portfolio/user_portfolio.html
{% extends "base.html" %} {% block content %}
<!-- Page Wrapper -->
<div id="wrapper">
  <!-- Sidebar -->
  <ul
    class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
    id="accordionSidebar"
  >
    <!-- Sidebar - Brand -->
    <a
      class="sidebar-brand d-flex align-items-center justify-content-center"
      href="index.html"
    >
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0" />

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
      <a class="nav-link" href="index.html">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a
      >
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider" />

    <!-- Heading -->
    <div class="sidebar-heading">
      Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a
        class="nav-link collapsed"
        href="#"
        data-toggle="collapse"
        data-target="#collapseTwo"
        aria-expanded="true"
        aria-controls="collapseTwo"
      >
        <i class="fas fa-fw fa-cog"></i>
        <span>Components</span>
      </a>
      <div
        id="collapseTwo"
        class="collapse"
        aria-labelledby="headingTwo"
        data-parent="#accordionSidebar"
      >
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Custom Components:</h6>
          <a class="collapse-item" href="buttons.html">Buttons</a>
          <a class="collapse-item" href="cards.html">Cards</a>
        </div>
      </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
      <a
        class="nav-link collapsed"
        href="#"
        data-toggle="collapse"
        data-target="#collapseUtilities"
        aria-expanded="true"
        aria-controls="collapseUtilities"
      >
        <i class="fas fa-fw fa-wrench"></i>
        <span>Utilities</span>
      </a>
      <div
        id="collapseUtilities"
        class="collapse"
        aria-labelledby="headingUtilities"
        data-parent="#accordionSidebar"
      >
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Custom Utilities:</h6>
          <a class="collapse-item" href="utilities-color.html">Colors</a>
          <a class="collapse-item" href="utilities-border.html">Borders</a>
          <a class="collapse-item" href="utilities-animation.html"
            >Animations</a
          >
          <a class="collapse-item" href="utilities-other.html">Other</a>
        </div>
      </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider" />

    <!-- Heading -->
    <div class="sidebar-heading">
      Addons
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a
        class="nav-link collapsed"
        href="#"
        data-toggle="collapse"
        data-target="#collapsePages"
        aria-expanded="true"
        aria-controls="collapsePages"
      >
        <i class="fas fa-fw fa-folder"></i>
        <span>Pages</span>
      </a>
      <div
        id="collapsePages"
        class="collapse"
        aria-labelledby="headingPages"
        data-parent="#accordionSidebar"
      >
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Login Screens:</h6>
          <a class="collapse-item" href="login.html">Login</a>
          <a class="collapse-item" href="register.html">Register</a>
          <a class="collapse-item" href="forgot-password.html"
            >Forgot Password</a
          >
          <div class="collapse-divider"></div>
          <h6 class="collapse-header">Other Pages:</h6>
          <a class="collapse-item" href="404.html">404 Page</a>
          <a class="collapse-item" href="blank.html">Blank Page</a>
        </div>
      </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
      <a class="nav-link" href="charts.html">
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Charts</span></a
      >
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item active">
      <a class="nav-link" href="tables.html">
        <i class="fas fa-fw fa-table"></i>
        <span>Tables</span></a
      >
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block" />

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
  </ul>
  <!-- End of Sidebar -->

  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content">
      <!-- Topbar -->
      <nav
        class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
      >
        <!-- Sidebar Toggle (Topbar) -->
        <button
          id="sidebarToggleTop"
          class="btn btn-link d-md-none rounded-circle mr-3"
        >
          <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form
          class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
        >
          <div class="input-group">
            <input
              type="text"
              class="form-control bg-light border-0 small"
              placeholder="Search for..."
              aria-label="Search"
              aria-describedby="basic-addon2"
            />
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">
          <!-- Nav Item - Search Dropdown (Visible Only XS) -->
          <li class="nav-item dropdown no-arrow d-sm-none">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="searchDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div
              class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
              aria-labelledby="searchDropdown"
            >
              <form class="form-inline mr-auto w-100 navbar-search">
                <div class="input-group">
                  <input
                    type="text"
                    class="form-control bg-light border-0 small"
                    placeholder="Search for..."
                    aria-label="Search"
                    aria-describedby="basic-addon2"
                  />
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                      <i class="fas fa-search fa-sm"></i>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </li>
          <div class="topbar-divider d-none d-sm-block"></div>

          <!-- Nav Item - User Information -->
          <li class="nav-item dropdown no-arrow">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="userDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <span class="mr-2 d-none d-lg-inline text-gray-600 small"
                >{{ user.user_name }}</span
              >
              <img
                class="img-profile rounded-circle"
                src="https://source.unsplash.com/QAB-WJcbgJk/60x60"
              />
            </a>
            <!-- Dropdown - User Information -->

            <div
              class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
              aria-labelledby="userDropdown"
            >
              <a
                class="dropdown-item"
                href="{{ url_for('user_page.account_page') }}"
              >
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Profile
              </a>
              <div class="dropdown-divider"></div>
              <a
                class="dropdown-item"
                href="#"
                data-toggle="modal"
                data-target="#logoutModal"
              >
                <i
                  class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"
                ></i>
                Logout
              </a>
            </div>
          </li>
        </ul>
      </nav>
      <!-- End of Topbar -->

      <!-- Begin Page Content -->
      <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Total Value: ${{ total_value }}</h1>
        {% with messages = get_flashed_messages() %} {% if messages %}
        <p class="mb-4">{{ messages }}</p>
        {% endif %} {% endwith %}

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">
              <a href="{{ url_for('user_page.register_currency') }}"
                >Register Currency</a
              >
            </h6>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table
                class="table table-bordered"
                id="dataTable"
                width="100%"
                cellspacing="0"
              >
                <thead>
                  <tr>
                    <th>Currency</th>
                    <th>holdings</th>
                    <th>Price</th>
                    <th>Change</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>Currency</th>
                    <th>holdings</th>
                    <th>Price</th>
                    <th>Change</th>
                  </tr>
                </tfoot>
                <tbody>
                  {% if result and num_of_holds %} {% for currency, num_of_hold
                  in zip(result, num_of_holds) %}
                  <tr>
                    <td>
                      {{ currency["symbol"] }}
                      <a
                        class="small"
                        href="{{ url_for('user_page.update_currency', currency_name=currency['symbol']) }}"
                        >Add</a
                      >
                      <a
                        class="small"
                        href="{{ url_for('user_page.delete_currency', currency_name=currency['symbol']) }}"
                        >Delete</a
                      >
                    </td>
                    <td>{{ num_of_hold }}</td>
                    <td>${{ currency["price"] * num_of_hold }}</td>
                    <td>{{ currency["price_change_pct"] }}%</td>
                  </tr>
                  {% endfor %} {% endif %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- End of Main Content -->

    <!-- Footer -->
    <footer class="sticky-footer bg-white">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright &copy; Your Website 2019</span>
        </div>
      </div>
    </footer>
    <!-- End of Footer -->
  </div>
  <!-- End of Content Wrapper -->
</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div
  class="modal fade"
  id="logoutModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        Select "Logout" below if you are ready to end your current session.
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">
          Cancel
        </button>
        <a class="btn btn-primary" href="{{ url_for('user_page.logout') }}"
          >Logout</a
        >
      </div>
    </div>
  </div>
</div>

<!-- Page level plugins -->
<script
  type="text/javascript"
  src="{{ url_for('static', filename='vendor/datatables/jquery.dataTables.min.js') }}"
></script>
<script
  type="text/javascript"
  src="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap4.min.js') }}"
></script>

<!-- Page level custom scripts -->
<script
  type="text/javascript"
  src="{{ url_for('static', filename='js/demo/datatables-demo.js') }}"
></script>
{% endblock %}