api/app/forms/delete/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Email, InputRequired, EqualTo
from wtforms.fields.html5 import EmailField


class Delete(FlaskForm):
    username = StringField("Username", validators=[
        InputRequired("Please enter your name.")])
    email = EmailField("email", validators=[InputRequired(
        "Please enter your email adress."), Email("Require a valid email address")])

    password = PasswordField("Password", validators=[InputRequired(
        "Please enter your password"), EqualTo("confirm", message="password must match")])
    confirm = PasswordField("Repeat Password")

    submit = SubmitField("Delete")

api/app/forms/login/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Email, InputRequired, EqualTo
from wtforms.fields.html5 import EmailField


class Login(FlaskForm):
    username = StringField("Username", validators=[
        InputRequired("Please enter your name.")])
    email = EmailField("email", validators=[InputRequired(
        "Please enter your email adress."), Email("Require a valid email address")])

    password = PasswordField("Password", validators=[InputRequired(
        "Please enter your password"), EqualTo("confirm", message="password must match")])
    confirm = PasswordField("Repeat Password")

    remember_me = BooleanField("Remember me")
    submit = SubmitField("Login")

api/app/forms/signup/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Email, InputRequired, EqualTo
from wtforms.fields.html5 import EmailField
import re


def validate_username(self, username):
    """
    must be less tha 10 characters
    """

    if len(username.data) > 10:
        raise ValueError("Name must be less than 10 characters")


def validate_password(self, password):
    """
    Password
        - more than 8 less than 32 characters
        - have a upcase letter
        - have a special character
        - have a number
    """

    if len(password.data) < 8:
        raise ValueError("must be more than 8 characters")
    elif len(password.data) > 32:
        raise ValueError("must be less than 32 characters")
    elif re.search('[0-9]', password.data) is None:
        raise ValueError("Password must have a number")
    elif re.search('[A-Z]', password.data) is None:
        raise ValueError("Password must have a upcase letter")
    elif re.search('[@_!#$%^&*()<>?/\|}{~:]', password.data) is None:
        raise ValueError("Password must have a special character")


class SignupForm(FlaskForm):
    username = StringField("Username", validators=[
        InputRequired("Please enter your name."), validate_username])
    email = EmailField("Email", validators=[InputRequired(
        "Please enter your email adress."), Email("Require a valid email address")])

    password = PasswordField("Password", validators=[InputRequired(
        "Please enter your password"), EqualTo("confirm", message="password must match"), validate_password])
    confirm = PasswordField("Repeat Password")
    submit = SubmitField("Register Account")

api/app/forms/update/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Email, InputRequired, EqualTo
from wtforms.fields.html5 import EmailField
import re


def validate_new_username(self, new_username):
    """
    must be less tha 10 characters
    """

    if len(new_username.data) > 10:
        raise ValueError("Name must be less than 10 characters")


def validate_new_password(self, new_password):
    """
    PAssword
        - more than 8 less than 32 characters
        - have a upcase letter
        - have a special character
        - have a number
    """

    if len(new_password.data) < 8:
        raise ValueError("must be more than 8 characters")
    elif len(new_password.data) > 32:
        raise ValueError("must be less than 32 characters")
    elif re.search('[0-9]', new_password.data) is None:
        raise ValueError("Password must have a number")
    elif re.search('[A-Z]', new_password.data) is None:
        raise ValueError("Password must have a upcase letter")
    elif re.search('[@_!#$%^&*()<>?/\|}{~:]', new_password.data) is None:
        raise ValueError("Password must have a special character")


class Update(FlaskForm):
    # username = StringField("Username", validators=[InputRequired("Please enter your current user name.")])

    new_username = StringField("New Username", validators=[
        InputRequired("Please enter your new user name."), validate_new_username])

    # email = EmailField("Email", validators=[InputRequired("Please enter your current email address."), Email("Require a valid email address")])

    new_email = EmailField("New Email", validators=[InputRequired(
        "Please enter your new email address."), Email("Require a valid email address")])

    # password = PasswordField("Password", validators=[InputRequired("Please enter your current password")])

    new_password = PasswordField("New Password", validators=[InputRequired(
        "Please enter your new password"), EqualTo("confirm", message="password must match"), validate_new_password])

    confirm = PasswordField("Repeat Password")

    submit = SubmitField("Update")

api/app/views/views.py
from flask import Flask, Blueprint, request, session, jsonify
from app.forms.signup.forms import SignupForm
from app.forms.login.forms import Login
from app.forms.update.forms import Update
from app.forms.delete.forms import Delete
from app.utils.execute_user_db import UserService
from app.utils.execute_crypt_db import PortfolioService
from app.utils.execute_api import API
import json

user_page = Blueprint("user_page", __name__,
                      template_folder="templates")



@user_page.route("/signup", methods=["POST"])
def signup():
    # duplicete check user_name and user_mail
    user_service = UserService()
    error = user_service.register(json.loads(request.data))
    if error:
        return jsonify(ok=True)
    # alredy exist same user name or email
    return ""


@user_page.route("/login", methods=["POST"])
def login():
    # check if user already created a account
    user_service = UserService()
    user = user_service.login(json.loads(request.data))

    if user:
        session['user_id'] = user.user_id
        session['login'] = True

        print(session)
        # return user data
        return jsonify(id=user.user_id, username=user.user_name, mail=user.user_mail, password=user.user_password)
    # doesn't match post data with user info in db
    return ""


@user_page.route("/edit/<id>", methods=["PATCH"])
def edit(id):

    if session.get("user_id") != int(id):
        return ""

    user_service = UserService()
    response = user_service.update(json.loads(request.data), id)
    if response:
        return request.data

    return ""


@user_page.route("/delete/<id>", methods=["DELETE"])
def delete(id):

    if session.get("user_id") != int(id):
        return ""

    user_service = UserService()
    error = user_service.delete(id)
    if error:
        session.pop("user_id", None)
        session.pop("login", None)
        return jsonify(ok=True)
    return ""


@user_page.route("/fetch", methods=["GET"])
def fetch():

    if not is_login():
        return ""

    user_service = UserService()
    user = user_service.get_user_info_by_user_id(session["user_id"])

    return jsonify(id=user.user_id, username=user.user_name, email=user.user_mail, password=user.user_password)


@user_page.route("/refetch", methods=["GET"])
def refetch():

    if not is_login():
        return ""

    user_service = UserService()
    user = user_service.get_user_info_by_user_id(session["user_id"])

    return jsonify(id=user.user_id, username=user.user_name, email=user.user_mail, password=user.user_password)


@user_page.route("/logout/<id>", methods=["POST"])
def logout(id):

    if session.get("user_id") != int(id):
        return ""

    session.pop("user_id")
    session["login"] = False

    return jsonify(ok=True)


@user_page.route("/forgot_password", methods=["POST"])
def forgot_password():

    if not is_login():

        return ""

    response = json.loads(request.data)
    user_service = UserService()

    user = user_service.get_user_info_by_email(response["email"])

    if not user:
        return ""

    user_service.send_reset_mail(user)

    return jsonify(ok=True)


@user_page.route("/is_valid_token/<token>", methods=["POST"])
def is_valid_token(token):
    user_service = UserService()

    user = user_service.reset_password_by_token(token)
    if user is None:
        return ""

    return jsonify(ok=True)


@user_page.route("/reset_password/<token>", methods=["POST"])
def reset_password(token):
    form_data = json.loads(request.data)
    user_service = UserService()

    user = user_service.reset_password_by_token(token)
    if user is None:
        return ""

    result = user_service.register_new_password(user, form_data)
    if result:
        return jsonify(ok=True)
    return ""


@user_page.route("/fetch_currency", methods=["GET"])
def fetch_currency():
    if not is_login():

        return ""

    portfolio_service = PortfolioService()
    data = portfolio_service.get_user_portfolio(session["user_id"])
    if data:
        api = API()
        "data[0]: currency name, data[1]: number of hold currency"
        result = api.call_api(data[0])
        currency_list, total_value = api.data_process(result, data[1])
        return jsonify(id=session["user_id"], currency_list=currency_list, total_value=total_value)

    return jsonify(id=session["user_id"], currency_list="", total_value=0)


@user_page.route("/register_currency/<id>", methods=["POST"])
def register_currency(id):

    if not is_login():

        return ""

    request_data = json.loads(request.data)

    portfolio_service = PortfolioService()
    error = portfolio_service.register(
        id, request_data["symbol"].upper(), request_data["num_hold"])
    if error:
        return jsonify(ok=True)

    return ""


@user_page.route("/edit_currency/<id>", methods=["PATCH"])
def edit_currency(id):

    if not is_login():

        return ""

    edit_data = json.loads(request.data)
    portfolio_service = PortfolioService()
    result = portfolio_service.update_currency_data(
        id, edit_data["symbol"].upper(), edit_data["num_hold"])
    if result:

        return jsonify(json.loads(request.data))

    return ""


@user_page.route("/delete_currency/<id>/<currency>", methods=["DELETE"])
def delete_currency(id, currency):

    if not is_login():

        return ""

    portfolio_service = PortfolioService()
    result = portfolio_service.delete_currency_data(id, currency.upper())
    if result:
        return jsonify(ok=True)

    return ""


# Check login status
def is_login():
    return session["login"]

api/app/templates/user/account_page.html
{% extends "base.html" %} {% block content %} {% with messages =
get_flashed_messages() %} {% if messages %}
<p>
  {{ messages }}
</p>
{% endif %} {% endwith %}
<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Account</h1>
                </div>
                <div class="text-center">
                  <p>User Name: {{ user.user_name }}</p>
                </div>
                <div class="text-center">
                  <p>Mail: {{ user.user_mail }}</p>
                </div>
                <div class="text-center">
                  <a class="small" href="{{ url_for('user_page.update') }}"
                    >Update Account</a
                  >
                </div>
                <div class="text-center">
                  <a class="small" href="{{ url_for('user_page.delete') }}"
                    >Delete Account</a
                  >
                </div>
                <div class="text-center">
                  <a
                    class="small"
                    href="{{ url_for('user_page.user_portfolio') }}"
                  >
                    >Back to Portfolio</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

api/app/templates/user/delete.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              {% with messages = get_flashed_messages() %} {% if messages %}
              <p>
                {{ messages }}
              </p>
              {% endif %} {% endwith %}
              <h1 class="h4 text-gray-900 mb-4">Delete an Account</h1>
            </div>
            <form action="" method="post" class="user">
              {{ form.hidden_tag() }}
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {{ form.username.label }}<br />
                  {{ form.username(size=10, class="form-control
                  form-control-user", placeholder="User Name") }} {% if
                  form.username.errors %}
                  <ul class="username_errors">
                    {% for error in form.username.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                  {% endif %}
                </div>
              </div>
              <div class="form-group">
                {{ form.email.label }}<br />
                {{ form.email(class="form-control form-control-user",
                placeholder="Email Address") }}
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {{ form.password.label }}<br />
                  {{ form.password(size=32, class="form-control
                  form-control-user", placeholder="Password") }} {% if
                  form.password.errors %}
                  <ul class="password_errors">
                    {% for error in form.password.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                  {% endif %}
                </div>
                <div class="col-sm-6">
                  {{ form.confirm.label }}<br />
                  {{ form.confirm(size=32, class="form-control
                  form-control-user", placeholder="Repeat Password") }}
                </div>
              </div>
              {{ form.submit(class="btn btn-primary btn-user btn-block") }}
            </form>
            <div class="text-center">
              <a class="small" href="{{ url_for('user_page.account_page') }}">
                >Back to Account Page</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

api/app/templates/user/forgot_password.html
{% extends "base.html" %} {% block content %} {% with messages =
get_flashed_messages() %} {% if messages %}
<p>
  {{ messages }}
</p>
{% endif %} {% endwith %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                  <p class="mb-4">
                    We get it, stuff happens. Just enter your email address
                    below and we'll send you a link to reset your password!
                  </p>
                </div>
                <form class="user">
                  <div class="form-group">
                    <input
                      type="email"
                      class="form-control form-control-user"
                      id="exampleInputEmail"
                      aria-describedby="emailHelp"
                      placeholder="Enter Email Address..."
                    />
                  </div>
                  <a
                    href="login.html"
                    class="btn btn-primary btn-user btn-block"
                  >
                    Reset Password
                  </a>
                </form>
                <hr />
                <div class="text-center">
                  <a class="small" href="{{ url_for('user_page.signup') }}"
                    >Create an Account!</a
                  >
                </div>
                <div class="text-center">
                  <a class="small" href="{{ url_for('user_page.login') }}"
                    >Already have an account? Login!</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

api/app/templates/user/login.html
{% extends "base.html" %} {% block content %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  {% with messages = get_flashed_messages() %} {% if messages %}
                  <p>
                    {{ messages }}
                  </p>
                  {% endif %} {% endwith %}
                  <h1 class="h4 text-gray-900 mb-4">Login!</h1>
                </div>
                <form action="" method="post" class="user">
                  {{ form.hidden_tag() }}
                  <div class="form-group">
                    {{ form.username.label }}<br />
                    {{ form.username(size=10, class="form-control
                    form-control-user", placeholder="Enter Email User Name") }}
                  </div>
                  <div class="form-group">
                    {{ form.email.label }}<br />
                    {{ form.email(class="form-control form-control-user",
                    placeholder="Enter Email Address...") }}
                  </div>
                  <div class="form-group">
                    {{ form.password.label }}<br />
                    {{ form.password(size=32, class="form-control
                    form-control-user", placeholder="Password") }}
                  </div>
                  <div class="form-group">
                    {{ form.confirm.label }}<br />
                    {{ form.confirm(size=32, class="form-control
                    form-control-user", placeholder="Repeat Password") }}
                  </div>
                  <div class="form-group">
                    <div class="custom-control custom-checkbox small">
                      <input
                        type="checkbox"
                        class="custom-control-input"
                        id="customCheck"
                      />
                      <label class="custom-control-label" for="customCheck"
                        >Remember Me</label
                      >
                    </div>
                  </div>
                  {{ form.submit(class="btn btn-primary btn-user btn-block") }}
                  <hr />
                  <a
                    href="index.html"
                    class="btn btn-google btn-user btn-block"
                  >
                    <i class="fab fa-google fa-fw"></i> Login with Google
                  </a>
                  <a
                    href="index.html"
                    class="btn btn-facebook btn-user btn-block"
                  >
                    <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                  </a>
                </form>
                <hr />
                <div class="text-center">
                  <a
                    class="small"
                    href="{{ url_for('user_page.forgot_password') }}"
                    >Forgot Password?</a
                  >
                </div>
                <div class="text-center">
                  <a class="small" href="{{ url_for('user_page.signup') }}"
                    >Create an Account!</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

api/app/templates/user/signup.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              {% with messages = get_flashed_messages() %} {% if messages %}
              <p>
                {{ messages }}
              </p>
              {% endif %} {% endwith %}
              <h1 class="h4 text-gray-900 mb-4">Create an Account</h1>
            </div>
            <form action="" method="post" class="user">
              {{ form.hidden_tag() }}
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {{ form.username.label }}<br />
                  {{ form.username(size=10, class="form-control
                  form-control-user", placeholder="User Name") }} {% if
                  form.username.errors %}
                  <ul class="username_errors">
                    {% for error in form.username.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                  {% endif %}
                </div>
              </div>
              <div class="form-group">
                {{ form.email.label }}<br />
                {{ form.email(class="form-control form-control-user",
                placeholder="Email Address") }}
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {{ form.password.label }}<br />
                  {{ form.password(size=32, class="form-control
                  form-control-user", placeholder="Password") }} {% if
                  form.password.errors %}
                  <ul class="password_errors">
                    {% for error in form.password.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                  {% endif %}
                </div>
                <div class="col-sm-6">
                  {{ form.confirm.label }}<br />
                  {{ form.confirm(size=32, class="form-control
                  form-control-user", placeholder="Repeat Password") }}
                </div>
              </div>
              {{ form.submit(class="btn btn-primary btn-user btn-block") }}
            </form>
            <div class="text-center">
              <a class="small" href="{{ url_for('user_page.login') }}"
                >Already have an account? Login!</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

api/app/templates/user/update.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              {% with messages = get_flashed_messages() %} {% if messages %}
              <p>
                {{ messages }}
              </p>
              {% endif %} {% endwith %}
              <h1 class="h4 text-gray-900 mb-4">Update an Account</h1>
            </div>
            <form action="" method="post" class="user">
              {{ form.hidden_tag() }}
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {{ form.new_username.label }}<br />
                  {{ form.new_username(size=10, class="form-control
                  form-control-user", placeholder="New User Name") }} {% if
                  form.new_username.errors %}
                  <ul class="username_errors">
                    {% for error in form.new_username.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                  {% endif %}
                </div>
              </div>
              <div class="form-group">
                {{ form.new_email.label }}<br />
                {{ form.new_email(class="form-control form-control-user",
                placeholder="New Email Address") }}
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {{ form.new_password.label }}<br />
                  {{ form.new_password(size=32, class="form-control
                  form-control-user", placeholder="New Password") }} {% if
                  form.new_password.errors %}
                  <ul class="password_errors">
                    {% for error in form.new_password.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                  {% endif %}
                </div>
                <div class="col-sm-6">
                  {{ form.confirm.label }}<br />
                  {{ form.confirm(size=32, class="form-control
                  form-control-user", placeholder="Repeat Password") }}
                </div>
              </div>
              {{ form.submit(class="btn btn-primary btn-user btn-block") }}
            </form>
            <div class="text-center">
              <a class="small" href="{{ url_for('user_page.account_page') }}">
                >Back to Account Page</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}